CI: Force `make rewrite` to be synced with comitted files.

diff --git a/.github/workflows/hydra.yml b/.github/workflows/hydra.yml
--- a/.github/workflows/hydra.yml
+++ b/.github/workflows/hydra.yml
@@ -50,3 +50,15 @@ jobs:
         run: |
           source venv/bin/activate
           pytest -n auto
+      - name: Run make rewrite and check for unstaged changes
+        run: |
+          source venv/bin/activate
+          if ! make rewrite; then
+            echo "Error: 'make rewrite' command failed"
+            exit 1
+          fi
+          if [[ -n $(git status --porcelain) ]]; then
+            echo "Error: Unstaged changes detected after running 'make rewrite'"
+            git status
+            exit 1
+          fi
